---
name: Java CI

on:
  push:
    branches: [main,java]
  pull_request:
    branches: [main,java]

jobs:
  build:
    name: Build with Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build with docker-compose
        run: docker-compose build --force-rm
